### ISSUE TITLE
Move development packages to devdependencies.

### ISSUE THREAD

**Issue by jaskarancodes** [Shuttl-Tech/terrace.js#9]
Currently, the following packages are being installed as project dependencies -:
```
axios-mock-adapter
mock-local-storage
enzyme 
enzyme-adapter-react-16
```

Ideally, they should come under devDependencies.

**Comment by jayantbh** [comment]
Thanks! This is now done in https://github.com/Shuttl-Tech/terrace.js/commit/a3ec017e8544ffd8c1e5c1883b31ca8b2702e4c4.
